# version: '3.8'

services:
  # MongoDB - Source de données
  mongodb:
    image: mongo:7.0
    # container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: services_publics
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
    networks:
      - pipeline_network

  # PostgreSQL - Stockage des données traitées
  postgres:
    image: postgres:15
    # container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - pipeline_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Apache Airflow - Orchestration
  airflow-init:
    image: apache/airflow:2.8.0-python3.10
    # container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./data:/opt/data 
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true
    networks:
      - pipeline_network

  
  airflow-webserver:
    build: .
    # container_name: airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./data:/opt/data
      - ./scripts:/opt/airflow/scripts
      - ./jars:/opt/spark-jars:ro
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow webserver"
    networks:
      - pipeline_network


  airflow-scheduler:
    build: .
    # container_name: airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./scripts:/opt/airflow/scripts
      - ./jars:/opt/spark-jars:ro
      - ./data:/opt/data 
    command: >
      bash -c "airflow scheduler"
    networks:
      - pipeline_network

  # Spark Master
  # spark-master:
  #   image: apache/spark:3.5.1
  #   # container_name: spark-master
  #   # user: root
  #   command: >
  #     bash -c "
  #     mkdir -p /opt/data/raw/demandes /opt/data/processed &&
  #     chmod -R 777 /opt/data &&
  #     /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master --port 7077
  #     "
  #   ports:
  #     - "8081:8080"
  #     - "7077:7077"
  #   volumes:
  #     - ./spark_jobs:/opt/spark_jobs
  #     - ./data:/opt/data
  #     - ./jars:/opt/spark-jars:ro
  #   networks:
  #     - pipeline_network


  # # Spark Worker
  # spark-worker:
  #   image: apache/spark:3.5.1
  #   # container_name: spark-worker
  #   # user: root
  #   depends_on:
  #     - spark-master
  #   command: >
  #     bash -c "
  #     mkdir -p /opt/data/raw/demandes /opt/data/processed &&
  #     chmod -R 777 /opt/data &&
  #     /opt/spark/bin/spark-class
  #     org.apache.spark.deploy.worker.Worker
  #     spark://spark-master:7077
  #     "
  #   environment:
  #     - SPARK_WORKER_MEMORY=2G
  #     - SPARK_WORKER_CORES=2
  #   volumes:
  #     - ./spark_jobs:/opt/spark_jobs
  #     - ./data:/opt/data
  #     - ./jars:/opt/spark-jars:ro
  #   networks:
  #     - pipeline_network

volumes:
  mongodb_data:
  postgres_data:

networks:
  pipeline_network:
    driver: bridge